[check]
command:/usr/local/opnsense/scripts/additional/check-wan-gateway-loss.php
parameters:
type:script_output
message:Additional Check WAN
description:Check WAN gateway loss and switch gateway priorities
