[run]
command:/usr/local/opnsense/scripts/additional/controller-agent.php run-once --json
parameters:
type:script_output
message:Additional Controller Agent
description:Run OPNsense Central Controller agent once

[heartbeat]
command:/usr/local/opnsense/scripts/additional/controller-agent.php heartbeat --json
parameters:
type:script_output
message:Additional Controller Heartbeat
description:Send heartbeat to OPNsense Central Controller

[poll]
command:/usr/local/opnsense/scripts/additional/controller-agent.php poll --json
parameters:
type:script_output
message:Additional Controller Jobs Poll
description:Poll jobs from OPNsense Central Controller
