[check]
command:/usr/local/opnsense/scripts/additional/additional-updater.php --check --json
parameters:
type:script_output
message:Additional Update Check
description:Check Additional menu updates on GitHub

[update]
command:/usr/local/opnsense/scripts/additional/additional-updater.php --update --json
parameters:
type:script_output
message:Additional Update Install
description:Install Additional menu update from GitHub
