[status]
command:/usr/local/opnsense/scripts/additional/udp2raw-manager.php --status --json
parameters:
type:script_output
message:Additional udp2raw status
description:Get Additional udp2raw status

[start]
command:/usr/local/opnsense/scripts/additional/udp2raw-manager.php --start-all --json
parameters:
type:script_output
message:Additional udp2raw start
description:Start Additional udp2raw instances

[stop]
command:/usr/local/opnsense/scripts/additional/udp2raw-manager.php --stop-all --json
parameters:
type:script_output
message:Additional udp2raw stop
description:Stop Additional udp2raw instances

[restart]
command:/usr/local/opnsense/scripts/additional/udp2raw-manager.php --restart-all --json
parameters:
type:script_output
message:Additional udp2raw restart
description:Restart Additional udp2raw instances

[watchdog]
command:/usr/local/opnsense/scripts/additional/udp2raw-manager.php --watchdog --json
parameters:
type:script_output
message:Additional udp2raw watchdog
description:Run Additional udp2raw watchdog
