[wireguard]
command:/usr/local/opnsense/scripts/additional/check-wg-status.php --silent
parameters:
type:script_output
message:Additional Check Status WireGuard
description:Check WireGuard status and restart WireGuard if degraded

[tailscale]
command:/usr/local/opnsense/scripts/additional/check-tailscale-status.php --silent
parameters:
type:script_output
message:Additional Check Status Tailscale
description:Check Tailscale status and start or restart tailscaled if unavailable
