[update]
command:/usr/local/opnsense/scripts/additional/updategeoip.php --silent
parameters:
type:script_output
message:Additional GeoIP Update
description:Download GeoIP MMDB from fallback sources, convert it to alias ranges and refresh firewall aliases
