[update]
command:/usr/local/opnsense/scripts/additional/updategeoip.php --silent
parameters:
type:script_output
message:Additional GeoIP Update
description:Update GeoIP MMDB from configured fallback sources
